version: '3.9'

services:
  db:
    image: postgres:16
    platform: linux/arm64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_dev
    ports: ['5432:5432']
    volumes: ['pgdata_dev:/var/lib/postgresql/data']

  api:
    build:
      context: ./modules/api
      dockerfile: Dockerfile.dev
    platform: linux/arm64
    environment:
      DATABASE_URL: ecto://postgres:postgres@db:5432/inventory_dev
      PHX_HOST: localhost
      PHX_PORT: '4000'
      CORS_ORIGIN: http://localhost:5173
    volumes:
      - ./modules/api:/app
    depends_on: [db]
    ports: ['4000:4000']
    command: mix phx.server

  web:
    build:
      context: ./modules/web
      dockerfile: Dockerfile.dev
    platform: linux/arm64
    environment:
      VITE_API_BASE_URL: http://localhost:4000/api
    volumes:
      - ./modules/web:/app
    depends_on: [api]
    ports: ['5173:5173']
    command: pnpm dev

  traefik:
    image: traefik:v3.0
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports: ['80:80']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  pgdata_dev:
